#Playbook for self learning purpose

---
  - name: This palybook is to install apache2
    hosts: aws
    become: true
    tasks:
      - name: Install httpd service
        apt:
          name: apache2
          state: present
      - name: restart apache2 service
        service:
          name: apache2
          state: restarted
